Added apache http client support
mmazi/rescu pull request #148
Opened 2024-06-19 06:08 UTC by andre77

its just a first try to add the apache http client support
unit tests are failing due to mockito errors, no time unfortunately to fix that right now.

no need to accept the PR, just an idea, how to solve this one https://github.com/mmazi/rescu/issues/147

2025-01-10 15:57 UTC, andre77 commented
chances to accept this pr ?

2025-01-12 09:31 UTC, mmazi commented
This doesn't even seem to compile:

/rescu/src/main/java/si/mazi/rescu/HttpTemplate.java:297:23
java: cannot find symbol
  symbol:   class HttpURLConnection
  location: class si.mazi.rescu.HttpTemplate

2025-01-12 10:22 UTC, andre77 commented
weird indeed, will look into it

2025-01-12 18:10 UTC, andre77 commented
fixed the previous merge
at least the compiler is happy, unit tests are not green though

2025-01-12 18:25 UTC, andre77 commented
with the latest mockito version the unit tests are green

2025-01-17 11:17 UTC, mmazi reviewed
Thanks for the pull request! Here are my comments; most or all are rather trivial and should be easy to implement.

2025-01-17 11:17 UTC, mmazi commented on pom.xml
> +          <scope>provided</scope>
Why is the scope `provided`? Is this OK in general?

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/Config.java
> +    private static final String CONNECTION_TYPE = "rescu.http.connection_type";
Please use camelCase instead of underscores, to maintain consistency with existing names.

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +                 SSLSocketFactory sslSocketFactory, HostnameVerifier hostnameVerifier, OAuthConsumer oAuthConsumer, HttpConnectionType client) {
rename parameter `client` to `connectionType`

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +import org.slf4j.Logger;
Many of these import statements are unused, please remove

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        headers.forEach((name, value) -> request.addHeader(name, value));
May be simplified to `        headers.forEach(request::addHeader);`

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +            return;
Perhaps log a warning (or info) here:
"Content-Length header already present, ignoring the explicitly set value " + value

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +
Please move up where the method was previously

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/HttpConnection.java
> +    void addHeader(String key, String value);
Rename to `setHeader` as it overwrites any previously set header with the same key.

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +        //RescuHttpURLConnection connection = (RescuHttpURLConnection) new URL(urlString).openConnection(proxy);
remove

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +    public boolean ssl() {
rename to `isSsl`

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/HttpConnection.java
> +    void setSSLSocketFactory(SSLSocketFactory sslSocketFactory);
setSSLSocketFactory and setHostnameVerifier are javax.net-specific. I suggest they are replaced with a single method `configureForSsl`. The interface HttpConnection should be completely independent of javax.net dependencies (imports).

Edit: I see this can't be done without also making ClientConfig javax.net-independent. Let's just leave it as it is, but please write a  // TODO: should be made javax.net-independent

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        if (executed) {
It would be nice if this code were covered by some tests, as it is non-trivial. Consider extracting the code that doesn't actually try to connect to the internet to a separate method and writing a test for it.

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/HttpConnection.java
> +    void setDoOutput(boolean b);
Please remove the setDoOutput and setDoInput methods and replace them with:
void doFinalConfig(Integer contentLength);
Its Apache (or default) implementation should be empty, Java.impl should have:

            connection.setDoOutput(true);
            connection.setDoInput(true);

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +    @Override
add empty line

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +    /**
@Override should be after the javadoc (all methods), parameter name is wrong in javadoc

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +     // @TODO ???
Please check if this should use  requestConfig.setSocketTimeout(), or log a warning that this is ignored.

2025-01-17 11:17 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +            // @TODO ???
throw new UnsupportedOperationException("setting a SSLSocketFactory not supported in Apache client") if sslSocketFactory != null

2025-01-17 11:28 UTC, andre77 commented on pom.xml
> +          <scope>provided</scope>
scope: "optional" would be a better choice, but it is not available
the idea to have "provided" was, that, if one do not want to use httpclient by apache, you do not want to have this dependency at all
so basically, if you have the default java client, you do not have the extra dependency by httpclient, it reduces the amount of jar files on your application

but, for me it would be fine to drop this line, your call

2025-01-17 12:27 UTC, andre77 commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        if (executed) {
tbh, not sure, what exactly is to be tested here...

2025-01-17 12:44 UTC, mmazi commented on pom.xml
> +          <scope>provided</scope>
Isn't `<optional>true</optional>` a better approach?

2025-01-17 13:05 UTC, andre77 commented on pom.xml
> +          <scope>provided</scope>
of course it is
changed

2025-01-17 13:27 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +
I meant just moving it a few lines up in the file, but this is fine too IMO.

2025-01-17 13:31 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        if (executed) {
Could test that e.g. headers are correctly set, that the entity is correctly added etc. It's nice to have any non-trivial code at least covered with a simple test, so at least we know there will be no NPEs or similar banal errors. But it's acceptable to skip this if it turns out to be overly complicated to write.

2025-01-17 13:37 UTC, mmazi commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +import org.slf4j.Logger;
still there

2025-01-17 14:04 UTC, andre77 commented on src/main/java/si/mazi/rescu/HttpTemplate.java
> +import org.slf4j.Logger;
fixed

2025-01-21 10:24 UTC, mmazi requested changes

2025-01-21 10:24 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +            return res.getFirstHeader(name).getValue();
This will always throw a NPE as `res` is never assigned.

2025-01-21 10:24 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        // TODO ???
Remove todo, nothing to do here (empty method is ok). Can also be moved to the interface as the default implementation.

2025-01-21 10:24 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +    private void exec() {
Should declare throws IOException (and not wrap in RuntimeException) and possibly other useful exceptions

2025-01-21 10:24 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        } catch (Throwable e) {
Handle this better: IOException should be declared, non-checked exceptions should not be wrapped etc.

2025-01-21 10:24 UTC, mmazi commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +                .build();
client should be closed at the end. As it is AutoCloseable, try-with-resources should be used.

2025-01-21 11:02 UTC, andre77 commented
cool catches 👍

2025-01-21 12:04 UTC, merged

2025-01-21 12:08 UTC, mmazi commented
Please comment in #147 how to use this (set rescu.http.connectionType etc.)

2025-03-11 16:31 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
This try-with-resources will close the connection, and the this.response will be closed, after that, getInputStream() will not work as the connection and the stream are both closed. And result in this exception:
org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

2025-03-11 16:51 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        return response.getFirstHeader(name).getValue();
NPE here, if the header with the name is absent.

2025-03-11 18:45 UTC, mmazi commented
@sutra thanks. @andre77 can you please fix the above issues?

2025-03-11 19:15 UTC, andre77 commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
without going too deep into this, just one question:
have you tried it und received a ConnectionClosedException ?
using the implementation for quite some time and never seen this one.
could you provide test code to reproduce ?

2025-03-11 19:15 UTC, andre77 commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        return response.getFirstHeader(name).getValue();
will change, good catch

2025-03-11 23:53 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
When the response is chunked, the `org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected` will happen:

```
2025-03-11 23:34:04,820 TRACE  [main] s.m.r.HttpTemplate.receive:162 Header response property: key='Transfer-Encoding', value='[chunked]'
```

2025-03-12 06:18 UTC, andre77 commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
ok, i see the issue in theory, i mean without having reproduced it locally...
@sutra any suggestions? so, better not use the 'try-with-resources' so, the client is not closed?
feel free to make a PR

2025-03-12 17:11 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
I am considering to make the `HttpConnection` extends `java.io.Closeable` and close the resources in the `close` method.

2025-03-12 17:24 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
A demo to consume the chunked response: https://github.com/sutra/webflux-demo

mvn spring-boot:run
and then run the ApacheConnectionTest

you will see the `testApacheConnectionChunked` failed.

2025-03-12 17:27 UTC, andre77 commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
again, thank you for the catch, and i see the problem
> any suggestions? so, better not use the 'try-with-resources' so, the client is not closed?
> feel free to make a PR

2025-03-12 17:35 UTC, sutra commented on src/main/java/si/mazi/rescu/clients/ApacheConnection.java
> +        try ( CloseableHttpClient client = clientBuilder.build() ) {
Created a PR #152